# Generated by Django 5.0.4 on 2024-07-08 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_item_height_alter_item_postal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='house_no',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
