# Generated by Django 5.0.4 on 2024-07-08 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_item_house_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='motherext',
        ),
    ]
